name: Build Testing

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download source
        uses: actions/checkout@v2
      
      - name: Install Termbox library
        run: sudo apt-get -qy install libtermbox-dev

      - name: Install Crystal
        uses: oprypin/install-crystal@v1.4.0
        with:
          crystal: latest

      - name: Build example
        run: crystal build src/init.cr
